# Generated by Django 5.0.3 on 2024-03-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
    ]
